export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';

export const GET_NAVBAR_REQUEST = 'GET_NAVBAR_REQUEST';
export const GET_NAVBAR_SUCCESS = 'GET_NAVBAR_SUCCESS';
export const GET_NAVBAR_FAIL = 'GET_NAVBAR_FAIL';
