export const GET_HOME_TEXTS_REQUEST = 'GET_HOME_TEXTS_REQUEST';
export const GET_HOME_TEXTS_SUCCESS = 'GET_HOME_TEXTS_SUCCESS';
export const GET_HOME_TEXTS_FAIL = 'GET_HOME_TEXTS_FAIL';

export const GET_NAVBAR_REQUEST = 'GET_NAVBAR_REQUEST';
export const GET_NAVBAR_SUCCESS = 'GET_NAVBAR_SUCCESS';
export const GET_NAVBAR_FAIL = 'GET_NAVBAR_FAIL';

export const GET_FOOTER_REQUEST = 'GET_FOOTER_REQUEST';
export const GET_FOOTER_SUCCESS = 'GET_FOOTER_SUCCESS';
export const GET_FOOTER_FAIL = 'GET_FOOTER_FAIL';
